- include: python.yml

- name: Configure the Server and install required software
# ========================================================
  hosts: localhost

  remote_user: 'root'
  become: true

  roles:
    - mumble-server
